version: "3"
services:
  

  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./configuration/prometheus/prometheus.yaml:/etc/prometheus.yaml
      - ./configuration/prometheus/rules.yml:/etc/rules.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    hostname: grafana 
    volumes:
      - ./configuration/grafana/grafana-bootstrap.ini:/etc/grafana/grafana.ini
      - ./configuration/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

